// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSRPnEaCy9BjMqAAZvm7NBQAScXaSzCg',
    appId: '1:727144727003:web:d20b04c9c944ff870967fe',
    messagingSenderId: '727144727003',
    projectId: 'ditonton-f5b3c',
    authDomain: 'ditonton-f5b3c.firebaseapp.com',
    storageBucket: 'ditonton-f5b3c.appspot.com',
    measurementId: 'G-5DZBB34D20',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRRqTydTm02s3FH2m2hrM-N-2sIpV96a8',
    appId: '1:727144727003:android:ea0c9046fd10a5880967fe',
    messagingSenderId: '727144727003',
    projectId: 'ditonton-f5b3c',
    storageBucket: 'ditonton-f5b3c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcfzj0mh4y2Nb1YPbRb0wFu2zbnsOpbm4',
    appId: '1:727144727003:ios:b130d981809f97140967fe',
    messagingSenderId: '727144727003',
    projectId: 'ditonton-f5b3c',
    storageBucket: 'ditonton-f5b3c.appspot.com',
    iosClientId: '727144727003-bg6781b0oeqsfu3jasc95tpr4g4u14lm.apps.googleusercontent.com',
    iosBundleId: 'com.dicoding.ditonton',
  );
}
